---
title: "FINAL_EXAM"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
MyCupid = read.csv("/Users/jiayingning/Downloads/MyCupid.csv")
```




```{r}
library(ggvis)
library(dplyr)
if (FALSE) {
  library(RSQLite)
  library(dbplyr)
}
```


```{r}
CupidDf <- MyCupid %>%
    mutate(cupid_name = row.names(MyCupid)) %>%
    select(cupid_name, offspring_1, sign,body_type,drinks,drugs,status,smokes)

ui <- fluidPage(
    titlePanel(""),
    
    sidebarLayout(
        sidebarPanel(
            textInput("name",
                      "YOUR Destiny"),
            selectInput("sign",
                        "sign",
                        choices = CupidDf$sign
            ),
            selectInput("body_type",
                        "Your preferred body type",
                        choices = CupidDf$body_type
            ),
            selectInput("status",
                        "Your preferred status",
                        choices = CupidDf$status
            ),
            selectInput("drinks",
                        "What kind of drinking frequency can you accept?",
                        choices = CupidDf$drinks
            ),
            selectInput("drugs",
                        "What kind of drugs habit can you accept?",
                        choices = CupidDf$drugs
            ),
            selectInput("smokes",
                        "Do you accept smoking behavior, if so what kind of smoking status can you accept?",
                        choices = CupidDf$smokes
            ),
            selectInput("offspring_1",
                        "Do you want Kids?",
                        choices = CupidDf$offspring_1)
        ),
        mainPanel(
            DT::dataTableOutput("table"),
            plotOutput("plot")
        )
    )
)

server <- function(input, output, session) {
    
    reactiveDf <- reactive({
        if (input$name == "" &
            input$offspring_1 == "") {
            return(CupidDf)
        }
        
        if (input$name != "") {
            CupidDf <- CupidDf %>%
                filter(
                    grepl(input$name, cupid_name, ignore.case = TRUE)
                )
            
        }
        
        if (input$offspring_1 != "") {
            CupidDf <- CupidDf %>%
                filter(
                    offspring_1 == input$offspring_1
                )
            
        }
        
        return(CupidDf)
    })
 conditional <- function(condition, success) {
    if (condition) success else TRUE
}

reactiveDf <- reactive({
  CupidDf %>%
    filter(
      conditional(input$name != "", grepl(input$name, cupid_name, ignore.case = TRUE)),
      conditional(input$sign != "", sign == input$sign),
      conditional(input$body_type != "", body_type == input$body_type),
      conditional(input$drinks != "", drinks == input$drinks),
      conditional(input$drugs != "", drugs == input$drugs),
      conditional(input$smokes != "", smokes == input$smokes),
      conditional(input$status != "", status == input$status),
      conditional(input$offspring_1 != "", offspring_1 == input$offspring_1)
    )
})

    output$table <- DT::renderDataTable({
        reactiveDf()
    })
    
}

shinyApp(ui, server)
```

